public class MyOBWrapper {
  public String CustomerId { get; set; }
  public String applicationId { get; set; }
  public String CustomerName { get; set; }
  public String Address { get; set; }
  public String PostalCode { get; set; }
  public String City { get; set; }
  public String Country { get; set; }
  public String CountryCode { get; set; }
  public String Email { get; set; }
  public String keyToken { get; set; }
  public String venueId { get; set; }
  public String FirstName { get; set; }
  public String LastName { get; set; }
  public String Phone { get; set; }
}