/*************************************************************************
* Author:           Richard Abendroth
* Author-Email:     development@incubes.com
* Author-Website:   www.incubes.com
*
* Name:             TriggerException
* Type:             Exception Class 
*
* Description:      - Exception class used if trigger util methods are called without a trigger context
*
* Changes:          2016-11-07: Created by Richard Abendroth
*************************************************************************/
public class OutOfTriggerContextException extends Exception{

}