/*************************************************************************
* Author:           Richard Abendroth
* Author-Email:     development@incubes.com
* Author-Website:   www.incubes.com
*
* Name:             TriggerException
* Type:             Exception Class 
*
* Description:      - Exception class for bulkified trigger pattern
*                   - See http://developer.force.com/cookbook/recipe/trigger-pattern-for-tidy-streamlined-bulkified-triggers
*                   for more details
*
* Changes:          2016-10-07: Created by Richard Abendroth
*************************************************************************/
public class TriggerException extends Exception {}